### PR TITLE
Little improvements

### LINKED ISSUE #29: Refresh on "Model Based" does not work because of prefixed id on captcha key field

### PR DESCRIPTION
**Pull request by kuldeepaggarwal**
1. Allow capability for user to add extra headers in response, like cross-origin.
2. use `(Time.now.to_f * 1_000_000_000).to_s` because 2 requests may occur at same time, so use nanoseconds.
3. If multiple captchas are on the same page, then unique id has been assigned to captcha_key. It will also fixed #29 automatically.
4. extract url cration logic and used in image and refresh_button link.

### CODE REVIEW

**Comment by kuldeepaggarwal** [comment]
ping @zealot128

**Comment by zealot128** [comment]
thanks for the contribution!

**Comment by kuldeepaggarwal** [comment]
@zealot128 Can we release a version for this?

**Comment by zealot128** [comment]
0.3.4 is now released.

**Pull request merged**
